name: myapp
description: "A new Flutter project."

# Impede publicação acidental no pub.dev
publish_to: 'none'

# Versão do app: major.minor.patch+build
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Backend e autenticação
  supabase_flutter: ^2.9.0
  supabase_auth_ui: ^0.5.5
  google_sign_in: ^6.3.0

  # Configuração de ambiente
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # build_runner é útil se você usar geração de código
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - .env
